In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
#read csv files in data
train = pd.read_csv('/content/drive/MyDrive/data/train.csv')
test= pd.read_csv('/content/drive/MyDrive/data/test.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
X = train.drop(columns=['price_doc'])
y = train[['price_doc']]

In [ ]:
#save row id in a dataframe
row_id = test['row ID']
#drop it from test now
test = test.drop(columns=['row ID'])

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

In [ ]:
numerical_features = train.select_dtypes(include=['float64', 'int64']).columns
categorical_features = train.select_dtypes(include=['object']).columns
#Create transformers for numerical and categorical features
numerical_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('ordinal', OrdinalEncoder())
])

# Combine transformers using ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Preprocess the training data
X_train_preprocessed = preprocessor.fit_transform(train)

In [ ]:
%pip install catboost
%pip install xgboost
%pip install lightgbm
from catboost import CatBoostClassifier
import xgboost as xgb
import lightgbm as lgb

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn import tree

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

In [ ]:
categorical_features = list(map(str, categorical_features))


In [ ]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [ ]:
train.drop(columns=['sub_area'], inplace=True)
test.drop(columns=['sub_area'], inplace=True)

In [ ]:
train.shape

(181507, 272)

In [ ]:
numerical_features = X.select_dtypes(include=['float64', 'int64']).columns


In [ ]:
categorical_features = X.select_dtypes(include=['object']).columns


In [ ]:
from sklearn.preprocessing import MinMaxScaler

# Create a scaler object
scaler = MinMaxScaler()

# Fit and transform the numeric columns
X_scaled = scaler.fit_transform(X[numerical_features])

# Create a new DataFrame with the scaled numeric columns
X_scaled_df = pd.DataFrame(X_scaled, columns=numerical_features)

# Concatenate the scaled numeric columns with the categorical columns
X_catboost = pd.concat([X_scaled_df, train[categorical_features]], axis=1)


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_catboost, y, test_size=0.2, random_state=42)

In [ ]:
# Install CatBoost using: pip install catboost
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from catboost import CatBoostRegressor, Pool
import numpy as np


# Create a CatBoostRegressor
catboost_model = CatBoostRegressor(iterations=1500,  # Number of boosting iterations
                                   learning_rate=0.01,  # Step size shrinkage used in update to prevent overfitting
                                   depth=8,  # Depth of the trees
                                   loss_function='RMSE',  # Loss function for regression
                                   cat_features=categorical_features,
                                   random_seed=2)  # Random seed for reproducibility

# Create a CatBoost Pool for training and testing data
train_pool = Pool(X_train, y_train, cat_features=categorical_features)
test_pool = Pool(X_test, y_test, cat_features=categorical_features)

# Fit the model on the training data
# Fit the model on the training data
catboost_model.fit(train_pool, eval_set=(test_pool), verbose=2)

# catboost_model.fit(X_train, y_train, eval_set=(X_test, y_test), verbose=2)

# Make predictions on the test set
predictions = catboost_model.predict(test_pool)

# Evaluate the model
mse = mean_squared_error(y_test, predictions)
rmse = np.sqrt(mse)
print("Root Mean squared error: %.2f" % rmse)

# You can also access feature importances
# feature_importances = catboost_model.feature_importances_
# print('Feature Importances:', feature_importances)
# bestTest = 12704833.59



In [ ]:
X

full_sq  life_sq  floor product_type        area_m  raion_popul  \
0          43.0     27.0    4.0   Investment  6.407578e+06     155572.0   
1          34.0     19.0    3.0   Investment  9.589337e+06     115352.0   
2          43.0     29.0    2.0   Investment  4.808270e+06     101708.0   
3          77.0     77.0    4.0   Investment  8.398461e+06     108171.0   
4          67.0     46.0   14.0   Investment  7.506452e+06      43795.0   
...         ...      ...    ...          ...           ...          ...   
181502     48.0     33.0    3.0   Investment  6.455617e+07       4949.0   
181503     48.0     33.0    3.0   Investment  6.455617e+07       4949.0   
181504     48.0     33.0    3.0   Investment  6.455617e+07       4949.0   
181505     48.0     33.0    3.0   Investment  6.455617e+07       4949.0   
181506     48.0     33.0    3.0   Investment  6.455617e+07       4949.0   

        green_zone_part  indust_part  children_preschool  \
0              0.189727     0.000070              9576.0   
1              0.372602     0.049637              6880.0   
2              0.112560     0.118537              5879.0   
3              0.015234     0.037316              5706.0   
4              0.007670     0.486246              2418.0   
...                 ...          ...                 ...   
181502         0.586175     0.005819               346.0   
181503         0.586175     0.005819               346.0   
181504         0.586175     0.005819               346.0   
181505         0.586175     0.005819               346.0   
181506         0.586175     0.005819               346.0   

        preschool_education_centers_raion  ...  cafe_count_5000_price_1500  \
0                                     5.0  ...                        40.0   
1                                     5.0  ...                        36.0   
2                                     4.0  ...                        25.0   
3                                     7.0  ...                       552.0   
4                                     2.0  ...                       155.0   
...                                   ...  ...                         ...   
181502                                0.0  ...                         0.0   
181503                                0.0  ...                         0.0   
181504                                0.0  ...                         0.0   
181505                                0.0  ...                         0.0   
181506                                0.0  ...                         0.0   

        cafe_count_5000_price_2500  cafe_count_5000_price_4000  \
0                              9.0                         4.0   
1                             15.0                         3.0   
2                             10.0                         3.0   
3                            319.0                       108.0   
4                             62.0                        14.0   
...                            ...                         ...   
181502                         0.0                         0.0   
181503                         0.0                         0.0   
181504                         0.0                         0.0   
181505                         0.0                         0.0   
181506                         0.0                         0.0   

        cafe_count_5000_price_high  big_church_count_5000  church_count_5000  \
0                              0.0                   13.0               22.0   
1                              0.0                   15.0               29.0   
2                              0.0                   11.0               27.0   
3                             17.0                  135.0              236.0   
4                              1.0                   53.0               78.0   
...                            ...                    ...                ...   
181502                         0.0                    0.0                2.0   
181503          

In [ ]:
# Fit and transform the numeric columns
t_scaled = scaler.fit_transform(test[numerical_features])

# Create a new DataFrame with the scaled numeric columns
t_scaled_df = pd.DataFrame(t_scaled, columns=numerical_features)

# Concatenate the scaled numeric columns with the categorical columns
t_catboost = pd.concat([t_scaled_df, test[categorical_features]], axis=1)

In [ ]:
testpro

array([[-0.32340286, -0.36267774, -0.17588081, ..., -0.63575423,
        -0.82935056, -0.85413114],
       [-0.38156632, -0.38639922, -0.10762265, ...,  0.3149459 ,
         1.04292725,  0.10763254],
       [-0.36975187, -0.38310457, -0.03936449, ..., -0.63575423,
        -0.66251393, -0.6617784 ],
       ...,
       [-0.36066382, -0.37387955, -0.58542979, ..., -0.63575423,
        -1.31132307, -1.43118935],
       [-0.36066382, -0.37387955, -0.58542979, ..., -0.63575423,
        -1.31132307, -1.43118935],
       [-0.36066382, -0.37387955, -0.58542979, ..., -0.63575423,
        -1.31132307, -1.43118935]])

In [ ]:
price_doc

array([12318207.49466547,  6601558.85078384,  4892828.67575628, ...,
        3226004.67467819,  3226004.67467819,  3226004.67467819])

In [ ]:
price_doc = catboost_model.predict(t_catboost)


In [ ]:
price_doc

array([12582718.80312871,  6677247.48072588,  5007287.66005988, ...,
        3159759.94510282,  3159759.94510282,  3159759.94510282])

In [ ]:
#Create a DataFrame for the predictions
predictions_df = pd.DataFrame(price_doc, columns=['price_doc'])

#Add the record ID from the test data to the predictions DataFrame
predictions_df.insert(0, 'row ID', row_id)

#Save the predictions to a CSV file
predictions_df.to_csv('download1me.csv', index=False)

In [ ]:
predictions_df.shape

(77789, 2)